Shader "Bloodlines/FactionColor"
{
    // Hand-written URP-compatible faction-color shader.
    //
    // Prompt brief asked for a Shader Graph (.shadergraph), but Shader Graph
    // assets are generated by the Unity editor UI, not authored as source.
    // For a scriptable, git-friendly infrastructure foundation we use a
    // hand-written URP .shader here with the same capability surface:
    //   - base albedo tint
    //   - per-instance faction tint blended against the base
    //   - silhouette rim light for RTS-zoom legibility
    //   - selection uniform (0 or 1) for highlight pop
    //
    // Entities.Graphics / URP batch rendering uses MaterialPropertyBlock
    // overrides through DOTS_INSTANCING_ON for per-instance properties so the
    // FactionTintComponent can drive _FactionColor without material cloning.
    Properties
    {
        _BaseColor      ("Base Color",      Color)  = (0.72, 0.72, 0.72, 1.0)
        _BaseMap        ("Base Map",        2D)     = "white" {}
        _FactionColor   ("Faction Tint",    Color)  = (0.5, 0.55, 0.70, 1.0)
        _FactionTintStrength ("Faction Tint Strength", Range(0, 1)) = 0.55
        _RimColor       ("Rim Color",       Color)  = (1.0, 1.0, 1.0, 1.0)
        _RimStrength    ("Rim Strength",    Range(0, 2)) = 0.75
        _RimPower       ("Rim Power",       Range(0.1, 8)) = 2.5
        _SelectionHighlight ("Selection Highlight", Range(0, 1)) = 0.0
        _SelectionColor ("Selection Color", Color) = (1.0, 0.94, 0.55, 1.0)
    }

    SubShader
    {
        Tags
        {
            "RenderType"      = "Opaque"
            "RenderPipeline"  = "UniversalPipeline"
            "Queue"           = "Geometry"
            "IgnoreProjector" = "True"
        }
        LOD 200

        Pass
        {
            Name "ForwardLit"
            Tags { "LightMode" = "UniversalForward" }

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma multi_compile_instancing
            #pragma multi_compile _ DOTS_INSTANCING_ON

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"

            struct Attributes
            {
                float4 positionOS : POSITION;
                float3 normalOS   : NORMAL;
                float2 uv         : TEXCOORD0;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            struct Varyings
            {
                float4 positionHCS : SV_POSITION;
                float3 positionWS  : TEXCOORD0;
                float3 normalWS    : TEXCOORD1;
                float2 uv          : TEXCOORD2;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            TEXTURE2D(_BaseMap); SAMPLER(sampler_BaseMap);

            CBUFFER_START(UnityPerMaterial)
                float4 _BaseColor;
                float4 _BaseMap_ST;
                float4 _FactionColor;
                float  _FactionTintStrength;
                float4 _RimColor;
                float  _RimStrength;
                float  _RimPower;
                float  _SelectionHighlight;
                float4 _SelectionColor;
            CBUFFER_END

            #ifdef UNITY_DOTS_INSTANCING_ENABLED
                UNITY_DOTS_INSTANCING_START(MaterialPropertyMetadata)
                    UNITY_DOTS_INSTANCED_PROP(float4, _BaseColor)
                    UNITY_DOTS_INSTANCED_PROP(float4, _FactionColor)
                    UNITY_DOTS_INSTANCED_PROP(float , _FactionTintStrength)
                    UNITY_DOTS_INSTANCED_PROP(float4, _RimColor)
                    UNITY_DOTS_INSTANCED_PROP(float , _RimStrength)
                    UNITY_DOTS_INSTANCED_PROP(float , _RimPower)
                    UNITY_DOTS_INSTANCED_PROP(float , _SelectionHighlight)
                    UNITY_DOTS_INSTANCED_PROP(float4, _SelectionColor)
                UNITY_DOTS_INSTANCING_END(MaterialPropertyMetadata)
                #define _BaseColor            UNITY_ACCESS_DOTS_INSTANCED_PROP_WITH_DEFAULT(float4, _BaseColor)
                #define _FactionColor         UNITY_ACCESS_DOTS_INSTANCED_PROP_WITH_DEFAULT(float4, _FactionColor)
                #define _FactionTintStrength  UNITY_ACCESS_DOTS_INSTANCED_PROP_WITH_DEFAULT(float , _FactionTintStrength)
                #define _RimColor             UNITY_ACCESS_DOTS_INSTANCED_PROP_WITH_DEFAULT(float4, _RimColor)
                #define _RimStrength          UNITY_ACCESS_DOTS_INSTANCED_PROP_WITH_DEFAULT(float , _RimStrength)
                #define _RimPower             UNITY_ACCESS_DOTS_INSTANCED_PROP_WITH_DEFAULT(float , _RimPower)
                #define _SelectionHighlight   UNITY_ACCESS_DOTS_INSTANCED_PROP_WITH_DEFAULT(float , _SelectionHighlight)
                #define _SelectionColor       UNITY_ACCESS_DOTS_INSTANCED_PROP_WITH_DEFAULT(float4, _SelectionColor)
            #endif

            Varyings vert(Attributes IN)
            {
                Varyings OUT = (Varyings)0;
                UNITY_SETUP_INSTANCE_ID(IN);
                UNITY_TRANSFER_INSTANCE_ID(IN, OUT);

                VertexPositionInputs posInputs  = GetVertexPositionInputs(IN.positionOS.xyz);
                VertexNormalInputs   normInputs = GetVertexNormalInputs(IN.normalOS);

                OUT.positionHCS = posInputs.positionCS;
                OUT.positionWS  = posInputs.positionWS;
                OUT.normalWS    = normInputs.normalWS;
                OUT.uv          = TRANSFORM_TEX(IN.uv, _BaseMap);
                return OUT;
            }

            float4 frag(Varyings IN) : SV_Target
            {
                UNITY_SETUP_INSTANCE_ID(IN);

                float3 albedo = SAMPLE_TEXTURE2D(_BaseMap, sampler_BaseMap, IN.uv).rgb * _BaseColor.rgb;

                // Blend faction tint into albedo for readable silhouettes.
                float tintStrength = saturate(_FactionTintStrength);
                albedo = lerp(albedo, albedo * _FactionColor.rgb, tintStrength);

                // Basic URP lambert using the main directional light.
                Light mainLight = GetMainLight();
                float3 normalWS = normalize(IN.normalWS);
                float  ndl      = saturate(dot(normalWS, mainLight.direction));
                float3 litColor = albedo * (mainLight.color.rgb * ndl + UNITY_LIGHTMODEL_AMBIENT.rgb * 0.65);

                // Silhouette rim for RTS-zoom legibility.
                float3 viewDirWS = normalize(GetCameraPositionWS() - IN.positionWS);
                float  rim       = 1.0 - saturate(dot(normalWS, viewDirWS));
                rim              = pow(rim, max(0.1, _RimPower));
                litColor += _RimColor.rgb * rim * _RimStrength * saturate(_FactionColor.rgb + 0.35);

                // Selection highlight pops to gold when _SelectionHighlight is 1.
                float selection = saturate(_SelectionHighlight);
                litColor = lerp(litColor, _SelectionColor.rgb, selection * 0.35);

                return float4(litColor, 1.0);
            }
            ENDHLSL
        }
    }

    Fallback "Universal Render Pipeline/Lit"
}
