using Unity.Collections;
using Unity.Entities;

namespace Bloodlines.Components
{
    /// <summary>
    /// Canonical unit type identity for a unit entity.
    /// Maps to an entry in _Bloodlines/Data/Units/*.asset (ScriptableObject generated by
    /// JsonContentImporter from data/units.json). Browser runtime equivalent: unit.typeId.
    ///
    /// Enumerated role values follow canonical browser role strings so behavior systems
    /// can dispatch uniformly. Unknown roles should never reach runtime; the JSON importer
    /// is authoritative.
    /// </summary>
    public struct UnitTypeComponent : IComponentData
    {
        public FixedString64Bytes TypeId;
        public UnitRole Role;
        public SiegeClass SiegeClass;
        public int PopulationCost;
        public int Stage;
    }

    public enum UnitRole : byte
    {
        Worker = 0,
        Melee = 1,
        MeleeRecon = 2,
        Ranged = 3,
        UniqueMelee = 4,
        LightCavalry = 5,
        SiegeEngine = 6,
        SiegeSupport = 7,
        EngineerSpecialist = 8,
        Support = 9,
        Unknown = 255,
    }

    public enum SiegeClass : byte
    {
        None = 0,
        Ram = 1,
        SiegeTower = 2,
        Trebuchet = 3,
        Ballista = 4,
        Mantlet = 5,
    }
}
