#!/usr/bin/env python3
"""
Build BLOODLINES_COMPLETE_MASTER_2026-04-14.md — the EVERYTHING master.

This augments the BLOODLINES_COMPLETE_BIBLE_ALL_v2.0 master (produced by
scripts/build_complete_bible.py) with the full runtime code, data, tests,
tasks, and build scripts that the v2.0 master deliberately excluded. The
result is a single file that contains every piece of design canon AND
every piece of implementation artifact. No session work is lost.

Both this script and build_complete_bible.py are idempotent.

Usage:
    python scripts/_build_everything_master.py

Output:
    18_EXPORTS/BLOODLINES_COMPLETE_MASTER_2026-04-14.md
"""

from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parent.parent
EXPORTS = ROOT / "18_EXPORTS"
ALL_V2 = EXPORTS / "BLOODLINES_COMPLETE_BIBLE_ALL_v2.0_2026-04-14.md"
OUT = EXPORTS / "BLOODLINES_COMPLETE_MASTER_2026-04-14.md"
CANONICAL_DISPLAY_ROOT = r"D:\ProjectsHome\Bloodlines"

assert ALL_V2.exists(), f"Source master missing: {ALL_V2}"


def read_text_or_bytes(path):
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_bytes().decode("utf-8", errors="replace")


def collect(parts_label, parts_title, patterns, extra_note=""):
    """Collect files matching the patterns (relative to ROOT)."""
    files = []
    for pattern, recursive in patterns:
        if recursive:
            files.extend(sorted(ROOT.glob(pattern)))
        else:
            # Non-recursive glob using direct Path
            parent = ROOT / pattern.rsplit("/", 1)[0] if "/" in pattern else ROOT
            name_pat = pattern.rsplit("/", 1)[-1] if "/" in pattern else pattern
            files.extend(sorted(parent.glob(name_pat)))
    files = [f for f in files if f.is_file()]
    seen = set()
    dedup = []
    for f in files:
        if f not in seen:
            seen.add(f)
            dedup.append(f)
    if not dedup:
        return ""
    out = [f"\n## PART {parts_label} — {parts_title}\n"]
    if extra_note:
        out.append(f"\n{extra_note}\n")
    out.append(f"\n*{len(dedup)} file(s) included in this part.*\n")
    for f in dedup:
        rel = f.relative_to(ROOT).as_posix()
        content = read_text_or_bytes(f)
        lines = content.count("\n")
        byte_count = len(content.encode("utf-8", errors="replace"))
        out.append("\n---\n\n")
        out.append(f"### FILE: `{rel}`\n")
        out.append(f"*{lines} lines, {byte_count:,} bytes.*\n\n")
        ext = f.suffix.lstrip(".")
        code_fence_lang = {
            "js": "javascript",
            "mjs": "javascript",
            "cjs": "javascript",
            "ts": "typescript",
            "tsx": "tsx",
            "jsx": "jsx",
            "py": "python",
            "json": "json",
            "css": "css",
            "html": "html",
            "sh": "bash",
            "cs": "csharp",
            "txt": "",
            "md": "",
            "yml": "yaml",
            "yaml": "yaml",
            "toml": "toml",
            "xml": "xml",
        }.get(ext.lower(), "")
        if code_fence_lang:
            out.append(f"```{code_fence_lang}\n")
            out.append(content.rstrip() + "\n")
            out.append("```\n")
        else:
            out.append(content.rstrip() + "\n")
    return "".join(out)


# --------------------------------------------------------------------------
# Assemble the everything master.
# --------------------------------------------------------------------------

now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

header = (
    "# BLOODLINES — COMPLETE MASTER 2026-04-14\n"
    "## Everything from both sessions. Design canon + runtime implementation.\n"
    "\n"
    f"**Version:** COMPLETE MASTER 2026-04-14\n"
    f"**Build timestamp:** {now}\n"
    f"**Source root:** `{CANONICAL_DISPLAY_ROOT}`\n"
    "**Generated by:** `scripts/_build_everything_master.py`\n"
    "\n"
    "---\n"
    "\n"
    "## What this document is\n"
    "\n"
    "This is the SINGLE file that contains every Bloodlines artifact from both concurrent "
    "2026-04-14 sessions without any loss of content.\n"
    "\n"
    "It begins with the full content of "
    "`18_EXPORTS/BLOODLINES_COMPLETE_BIBLE_ALL_v2.0_2026-04-14.md` (the canon-side master "
    "produced by the consolidation session, which absorbs every `.md` and relevant `.txt` "
    "file across the project's design archive, canon, creative branches, docs, and Unity "
    "implementation-planning material).\n"
    "\n"
    "It then extends that canon-side master with the implementation-side material that the "
    "v2.0 master deliberately omitted: the runtime code (`src/game/`), the data layer "
    "(`data/`), the test suite (`tests/`), the session task tracking (`tasks/`), and the "
    "build scripts (`scripts/`).\n"
    "\n"
    "Nothing from either session has been lost. Everything is present, verbatim, in a "
    "single readable export.\n"
    "\n"
    "Coordination provenance:\n"
    "\n"
    "- **Canon / consolidation session** produced: `01_CANON/BLOODLINES_DESIGN_BIBLE.md` "
    "(updated with Sections 16-24), `01_CANON/BLOODLINES_MASTER_MEMORY.md` (updated with "
    "Sections 92-93), `01_CANON/BLOODLINES_APPEND_ONLY_LOG.md` (updated), "
    "`scripts/build_complete_bible.py` (the v2.0 master generator), archived snapshots in "
    "`19_ARCHIVE/PRE_2026-04-14_CONSOLIDATION/`, viewer HTML updates, and web sync script "
    "updates.\n"
    "- **Runtime / implementation session** produced: `01_CANON/DEFENSIVE_FORTIFICATION_DOCTRINE.md`, "
    "`04_SYSTEMS/FORTIFICATION_SYSTEM.md`, `04_SYSTEMS/SIEGE_SYSTEM.md`, integration "
    "addenda in `TERRITORY_SYSTEM.md`, `DYNASTIC_SYSTEM.md`, `MATCH_STRUCTURE.md`, "
    "`UNIT_INDEX.md`, `MECHANICS_INDEX.md`, `SYSTEM_INDEX.md`, `CANONICAL_RULES.md`, "
    "`CANON_LOCK.md`, `docs/BLOODLINES_CURRENT_STATE_ANALYSIS.md`, "
    "`docs/DEFINITIVE_DECISIONS_REGISTER.md`, `docs/unity/PHASE_PLAN.md`, "
    "`docs/unity/SYSTEM_MAP.md`, the v3.3 bible export, a desktop copy of the v3.3 bible, "
    "the `00_ADMIN/CHANGE_LOG.md` Session 14 entry, and the Dynasty Consequence Cascade "
    "runtime implementation in `src/game/core/simulation.js`, `src/game/main.js`, "
    "`src/game/core/renderer.js`, `data/faiths.json`, `tests/runtime-bridge.mjs`, "
    "`tests/data-validation.mjs`.\n"
    "\n"
    "Both sessions honored the additive-only archival rules. No prior content was deleted, "
    "summarized, or reduced. Pre-consolidation snapshots are preserved in "
    "`19_ARCHIVE/PRE_2026-04-14_CONSOLIDATION/`.\n"
    "\n"
    "---\n"
    "\n"
    "# PART I — FULL CONTENT OF `BLOODLINES_COMPLETE_BIBLE_ALL_v2.0_2026-04-14.md`\n"
    "\n"
    "*Everything below through the end of Part I is reproduced verbatim from the v2.0 "
    "master. The Part X-style structure of the v2.0 master is preserved in full.*\n"
    "\n"
)

all_v2_content = ALL_V2.read_text(encoding="utf-8")

# Assemble Part II: runtime code, data, tests, tasks, scripts.
part_ii_header = (
    "\n"
    "---\n"
    "\n"
    "# PART II — RUNTIME IMPLEMENTATION ARTIFACTS\n"
    "\n"
    "*This part captures the implementation-side material that the canon-side v2.0 master "
    "deliberately omitted. Runtime code, data files, tests, tasks, and build scripts are "
    "all reproduced verbatim so the everything-master contains genuinely everything.*\n"
)

part_a = collect(
    "A (Runtime)",
    "Runtime Source Code (`src/`)",
    [("src/**/*.js", True), ("src/**/*.mjs", True), ("src/**/*.css", True), ("src/**/*.html", True)],
    extra_note=(
        "Browser-runtime source for the Bloodlines playable prototype. Canonical simulation "
        "logic, data loader, renderer, AI, and UI bridge. Includes the Dynasty Consequence "
        "Cascade landed on 2026-04-14."
    ),
)

part_b = collect(
    "B (Data)",
    "Data Layer (`data/`)",
    [("data/**/*.json", True)],
    extra_note=(
        "Data-first content definitions. Houses, units, buildings, resources, faiths (with "
        "2026-04-14 doctrine effect blocks for Light and Dark paths), conviction states, "
        "bloodline roles and paths, victory conditions, and map definitions."
    ),
)

part_c = collect(
    "C (Tests)",
    "Test Suite (`tests/`)",
    [("tests/**/*.mjs", True), ("tests/**/*.js", True)],
    extra_note=(
        "Validation tests. `data-validation.mjs` validates the data layer shape and "
        "canonical invariants. `runtime-bridge.mjs` (new 2026-04-14) simulates the dynasty "
        "cascade end-to-end and asserts capture, succession, captive ledger, ransom trickle, "
        "and governor-loss behavior."
    ),
)

part_d = collect(
    "D (Tasks)",
    "Session Task Tracking (`tasks/`)",
    [("tasks/*.md", False)],
    extra_note="Per-session todo and lessons files used for continuity.",
)

part_e = collect(
    "E (Scripts)",
    "Build, Sync, and Utility Scripts (`scripts/`)",
    [("scripts/*.py", False), ("scripts/*.sh", False), ("scripts/*.html", False)],
    extra_note=(
        "Project build and sync scripts. Includes `build_complete_bible.py` (v2.0 master "
        "generator), `_build_everything_master.py` (this everything-master generator), "
        "`_expand_bible_v33.py` (v3.3 expansion utility), `add_sections_80_81.py` "
        "(historical add-sections utility), `bloodlines_viewer.html` (design bible viewer), "
        "and `sync-to-web.sh` (web deploy sync)."
    ),
)

part_f = collect(
    "F (Unity Source Shell)",
    "Unity Project Shell (`unity/Assets/_Bloodlines/`)",
    [
        ("unity/Assets/_Bloodlines/**/*.cs", True),
        ("unity/Assets/_Bloodlines/**/*.asmdef", True),
        ("unity/README.md", False),
    ],
    extra_note=(
        "Unity implementation shell scaffolding from the Unity migration track. Includes "
        "`BloodlinesDefinitions.cs` and `JsonContentImporter.cs` which carry prototype faith "
        "effect data into Unity. Unity project itself lives at `unity/` and is summarized "
        "by its README; full Unity binary assets, packages, and settings are not included "
        "here (they are not canonical design documents)."
    ),
)


footer = (
    "\n"
    "---\n"
    "\n"
    "## End of Bloodlines Complete Master 2026-04-14\n"
    "\n"
    "This single file contains every design artifact and every runtime implementation "
    "artifact from both 2026-04-14 sessions. Nothing has been lost. Both sessions' work "
    "is preserved verbatim.\n"
    "\n"
    "If either session's work changes, regenerate the canon-side ALL v2.0 first "
    "(`python scripts/build_complete_bible.py`), then regenerate this everything-master "
    "(`python scripts/_build_everything_master.py`). Both scripts are deterministic and "
    "idempotent.\n"
    "\n"
)

final = header + all_v2_content + part_ii_header + part_a + part_b + part_c + part_d + part_e + part_f + footer

OUT.write_text(final, encoding="utf-8")
print(f"Wrote {OUT}")
print(f"  Size: {len(final.encode('utf-8')):,} bytes")
print(f"  Lines: {final.count(chr(10)):,}")
